### ISSUE TITLE
error.vue does not render

### ISSUE THREAD

**Issue by teddy-mczieuwa** [davideast/nuxt-firebase#4]
Hi, I successfully deployed my website using nuxt and firebase hosting. Unfortunately, whenever I visit a page that does not exist, my error.vue file does not render. The page does not even change. It remains on the same page. Is there some additional setting that I am missing?

**Comment by asg5704-deprecated** [comment]
I believe it has to do with the Vue router configuration. Hopefully these guide you in the right direction. https://router.vuejs.org/guide/essentials/history-mode.html#caveat

https://nuxtjs.org/api/configuration-router/

**Comment by teddy-mczieuwa** [comment]
Thanks, all fixed
